const fs = require('fs');
const path = require('path');

// Load .env file
require('dotenv').config({ path: path.resolve(__dirname, '../.env') });

const isProd = process.argv.includes('--prod');

const envContent = `// This file is auto-generated by scripts/set-env.js — DO NOT edit manually
export const environment = {
  production: ${isProd},
  apiUrl: '${process.env['API_URL'] || ''}',
  supabaseUrl: '${process.env['SUPABASE_URL'] || ''}',
  supabaseAnonKey: '${process.env['SUPABASE_ANON_KEY'] || ''}',
};
`;

const targetPath = isProd
  ? path.resolve(__dirname, '../src/environments/environment.prod.ts')
  : path.resolve(__dirname, '../src/environments/environment.ts');

fs.writeFileSync(targetPath, envContent);
console.log(`Generated ${targetPath}`);
